version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pswd
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    links:
      - postgres
    ports:
      - 8081:8080